const colors = {
  light: {
    text: "#EDEDED",
    tint: "#FF5E00",
    background: "#1F1D1D",
    foreground: "#EDEDED",
    card: "#242222",
    cardForeground: "#EDEDED",
    primary: "#FF5E00",
    primaryForeground: "#FFFFFF",
    secondary: "#292727",
    secondaryForeground: "#EDEDED",
    muted: "#2B2929",
    mutedForeground: "#A6A6A8",
    accent: "#292727",
    accentForeground: "#EDEDED",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#333333",
    input: "#292727",
  },
  dark: {
    text: "#EDEDED",
    tint: "#FF5E00",
    background: "#1F1D1D",
    foreground: "#EDEDED",
    card: "#242222",
    cardForeground: "#EDEDED",
    primary: "#FF5E00",
    primaryForeground: "#FFFFFF",
    secondary: "#292727",
    secondaryForeground: "#EDEDED",
    muted: "#2B2929",
    mutedForeground: "#A6A6A8",
    accent: "#292727",
    accentForeground: "#EDEDED",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#333333",
    input: "#292727",
  },
  radius: 12,
};

export default colors;
